
#define DEFINE_GLOBALS
#include "vga.h"
#include "main.h"

 char CHAR_SPACE[6][4] = {
    {BLACK,BLACK,BLACK,BLACK},
    {BLACK,BLACK,BLACK,BLACK},
    {BLACK,BLACK,BLACK,BLACK},
    {BLACK,BLACK,BLACK,BLACK},
    {BLACK,BLACK,BLACK,BLACK},
    {BLACK,BLACK,BLACK,BLACK}
};

 char CHAR_A_UP[6][4] = {
    {BLACK,WHITE,WHITE,BLACK},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,WHITE,WHITE,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE}
};

 char CHAR_B_UP[6][4] = {
    {WHITE,WHITE,WHITE,BLACK},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,WHITE,WHITE,BLACK},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,WHITE,WHITE,BLACK}
};

 char CHAR_C_UP[6][4] = {
    {BLACK,WHITE,WHITE,BLACK},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,BLACK},
    {WHITE,BLACK,BLACK,BLACK},
    {BLACK,WHITE,WHITE,BLACK},
    {WHITE,BLACK,BLACK,WHITE}
};

 char CHAR_D_UP[6][4] = {
    {WHITE,WHITE,WHITE,BLACK},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,WHITE,WHITE,BLACK}
};

 char CHAR_E_UP[6][4] = {
    {WHITE,WHITE,WHITE,WHITE},
    {WHITE,BLACK,BLACK,BLACK},
    {WHITE,WHITE,WHITE,WHITE},
    {WHITE,BLACK,BLACK,BLACK},
    {WHITE,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE}
};

 char CHAR_F_UP[6][4] = {
    {WHITE,WHITE,WHITE,WHITE},
    {WHITE,BLACK,BLACK,BLACK},
    {WHITE,BLACK,BLACK,BLACK},
    {WHITE,WHITE,WHITE,BLACK},
    {WHITE,BLACK,BLACK,BLACK},
    {WHITE,BLACK,BLACK,BLACK}
};

 char CHAR_G_UP[6][4] = {
    {BLACK,WHITE,WHITE,BLACK},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,BLACK},
    {WHITE,BLACK,WHITE,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {BLACK,WHITE,WHITE,BLACK}
};

 char CHAR_H_UP[6][4] = {
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,WHITE,WHITE,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE}
};

 char CHAR_I_UP[6][4] = {
    {BLACK,BLACK,WHITE,BLACK},
    {BLACK,BLACK,WHITE,BLACK},
    {BLACK,BLACK,WHITE,BLACK},
    {BLACK,BLACK,WHITE,BLACK},
    {BLACK,BLACK,WHITE,BLACK},
    {BLACK,BLACK,WHITE,BLACK}
};

 char CHAR_J_UP[6][4] = {
    {WHITE,WHITE,WHITE,WHITE},
    {BLACK,BLACK,WHITE,BLACK},
    {BLACK,BLACK,WHITE,BLACK},
    {BLACK,BLACK,WHITE,BLACK},
    {BLACK,BLACK,WHITE,BLACK},
    {WHITE,WHITE,BLACK,BLACK}
};

 char CHAR_K_UP[6][4] = {
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,WHITE,BLACK},
    {WHITE,WHITE,BLACK,BLACK},
    {WHITE,BLACK,WHITE,BLACK},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE}
};

 char CHAR_L_UP[6][4] = {
    {WHITE,BLACK,BLACK,BLACK},
    {WHITE,BLACK,BLACK,BLACK},
    {WHITE,BLACK,BLACK,BLACK},
    {WHITE,BLACK,BLACK,BLACK},
    {WHITE,BLACK,BLACK,BLACK},
    {WHITE,WHITE,WHITE,WHITE}
};

 char CHAR_M_UP[6][4] = {
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,WHITE,WHITE,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE}
};

 char CHAR_N_UP[6][4] = {
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,WHITE,BLACK,WHITE},
    {WHITE,BLACK,WHITE,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE}
};

 char CHAR_O_UP[6][4] = {
    {BLACK,WHITE,WHITE,BLACK},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {BLACK,WHITE,WHITE,BLACK}
};

 char CHAR_P_UP[6][4] = {
    {WHITE,WHITE,WHITE,BLACK},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,WHITE,WHITE,BLACK},
    {WHITE,BLACK,BLACK,BLACK},
    {WHITE,BLACK,BLACK,BLACK}
};

 char CHAR_Q_UP[6][4] = {
    {BLACK,WHITE,WHITE,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,WHITE,WHITE},
    {BLACK,WHITE,WHITE,BLACK},
    {BLACK,BLACK,BLACK,WHITE}
};

 char CHAR_R_UP[6][4] = {
    {WHITE,WHITE,WHITE,BLACK},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,WHITE,WHITE,BLACK},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE}
};

 char CHAR_S_UP[6][4] = {
    {BLACK,WHITE,WHITE,WHITE},
    {WHITE,BLACK,BLACK,BLACK},
    {BLACK,WHITE,WHITE,BLACK},
    {BLACK,BLACK,BLACK,WHITE},
    {BLACK,BLACK,BLACK,WHITE},
    {WHITE,WHITE,WHITE,BLACK}
};

 char CHAR_T_UP[6][4] = {
    {BLACK,WHITE,WHITE,WHITE},
    {BLACK,BLACK,WHITE,BLACK},
    {BLACK,BLACK,WHITE,BLACK},
    {BLACK,BLACK,WHITE,BLACK},
    {BLACK,BLACK,WHITE,BLACK},
    {BLACK,BLACK,WHITE,BLACK}
};

 char CHAR_U_UP[6][4] = {
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {BLACK,WHITE,WHITE,BLACK}
};

 char CHAR_V_UP[6][4] = {
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,WHITE,BLACK},
    {BLACK,WHITE,BLACK,BLACK}
};

 char CHAR_W_UP[6][4] = {
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,WHITE,WHITE,WHITE},
    {WHITE,BLACK,BLACK,WHITE}
};

 char CHAR_X_UP[6][4] = {
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {BLACK,WHITE,WHITE,BLACK},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE}
};

 char CHAR_Y_UP[6][4] = {
    {BLACK,WHITE,BLACK,WHITE},
    {BLACK,WHITE,BLACK,WHITE},
    {BLACK,WHITE,BLACK,WHITE},
    {BLACK,BLACK,WHITE,BLACK},
    {BLACK,BLACK,WHITE,BLACK},
    {BLACK,BLACK,WHITE,BLACK}
};

 char CHAR_Z_UP[6][4] = {
    {WHITE,WHITE,WHITE,WHITE},
    {BLACK,BLACK,BLACK,WHITE},
    {BLACK,BLACK,WHITE,BLACK},
    {BLACK,WHITE,BLACK,BLACK},
    {WHITE,BLACK,BLACK,BLACK},
    {WHITE,WHITE,WHITE,WHITE}
};