
#define DEFINE_GLOBALS
#include "vga.h"
#include "main.h"

 uint8_t CHAR_SPACE[6][4] = {
    {BLACK,BLACK,BLACK,BLACK},
    {BLACK,BLACK,BLACK,BLACK},
    {BLACK,BLACK,BLACK,BLACK},
    {BLACK,BLACK,BLACK,BLACK},
    {BLACK,BLACK,BLACK,BLACK},
    {BLACK,BLACK,BLACK,BLACK}
};

 uint8_t CHAR_A_UP[6][4] = {
    {BLACK,WHITE,WHITE,BLACK},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,WHITE,WHITE,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE}
};

 uint8_t CHAR_B_UP[6][4] = {
    {WHITE,WHITE,WHITE,BLACK},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,WHITE,WHITE,BLACK},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,WHITE,WHITE,BLACK}
};

 uint8_t CHAR_C_UP[6][4] = {
    {BLACK,WHITE,WHITE,BLACK},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,BLACK},
    {WHITE,BLACK,BLACK,BLACK},
    {BLACK,WHITE,WHITE,BLACK},
    {WHITE,BLACK,BLACK,WHITE}
};

 uint8_t CHAR_D_UP[6][4] = {
    {WHITE,WHITE,WHITE,BLACK},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,WHITE,WHITE,BLACK}
};

 uint8_t CHAR_E_UP[6][4] = {
    {WHITE,WHITE,WHITE,WHITE},
    {WHITE,BLACK,BLACK,BLACK},
    {WHITE,WHITE,WHITE,WHITE},
    {WHITE,BLACK,BLACK,BLACK},
    {WHITE,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE}
};

 uint8_t CHAR_F_UP[6][4] = {
    {WHITE,WHITE,WHITE,WHITE},
    {WHITE,BLACK,BLACK,BLACK},
    {WHITE,BLACK,BLACK,BLACK},
    {WHITE,WHITE,WHITE,BLACK},
    {WHITE,BLACK,BLACK,BLACK},
    {WHITE,BLACK,BLACK,BLACK}
};

 uint8_t CHAR_G_UP[6][4] = {
    {BLACK,WHITE,WHITE,BLACK},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,BLACK},
    {WHITE,BLACK,WHITE,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {BLACK,WHITE,WHITE,BLACK}
};

 uint8_t CHAR_H_UP[6][4] = {
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,WHITE,WHITE,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE}
};

 uint8_t CHAR_I_UP[6][4] = {
    {BLACK,BLACK,WHITE,BLACK},
    {BLACK,BLACK,WHITE,BLACK},
    {BLACK,BLACK,WHITE,BLACK},
    {BLACK,BLACK,WHITE,BLACK},
    {BLACK,BLACK,WHITE,BLACK},
    {BLACK,BLACK,WHITE,BLACK}
};

 uint8_t CHAR_J_UP[6][4] = {
    {WHITE,WHITE,WHITE,WHITE},
    {BLACK,BLACK,WHITE,BLACK},
    {BLACK,BLACK,WHITE,BLACK},
    {BLACK,BLACK,WHITE,BLACK},
    {BLACK,BLACK,WHITE,BLACK},
    {WHITE,WHITE,BLACK,BLACK}
};

 uint8_t CHAR_K_UP[6][4] = {
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,WHITE,BLACK},
    {WHITE,WHITE,BLACK,BLACK},
    {WHITE,BLACK,WHITE,BLACK},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE}
};

 uint8_t CHAR_L_UP[6][4] = {
    {WHITE,BLACK,BLACK,BLACK},
    {WHITE,BLACK,BLACK,BLACK},
    {WHITE,BLACK,BLACK,BLACK},
    {WHITE,BLACK,BLACK,BLACK},
    {WHITE,BLACK,BLACK,BLACK},
    {WHITE,WHITE,WHITE,WHITE}
};

 uint8_t CHAR_M_UP[6][4] = {
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,WHITE,WHITE,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE}
};

 uint8_t CHAR_N_UP[6][4] = {
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,WHITE,BLACK,WHITE},
    {WHITE,BLACK,WHITE,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE}
};

 uint8_t CHAR_O_UP[6][4] = {
    {BLACK,WHITE,WHITE,BLACK},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {BLACK,WHITE,WHITE,BLACK}
};

 uint8_t CHAR_P_UP[6][4] = {
    {WHITE,WHITE,WHITE,BLACK},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,WHITE,WHITE,BLACK},
    {WHITE,BLACK,BLACK,BLACK},
    {WHITE,BLACK,BLACK,BLACK}
};

 uint8_t CHAR_Q_UP[6][4] = {
    {BLACK,WHITE,WHITE,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,WHITE,WHITE},
    {BLACK,WHITE,WHITE,BLACK},
    {BLACK,BLACK,BLACK,WHITE}
};

 uint8_t CHAR_R_UP[6][4] = {
    {WHITE,WHITE,WHITE,BLACK},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,WHITE,WHITE,BLACK},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE}
};

 uint8_t CHAR_S_UP[6][4] = {
    {BLACK,WHITE,WHITE,WHITE},
    {WHITE,BLACK,BLACK,BLACK},
    {BLACK,WHITE,WHITE,BLACK},
    {BLACK,BLACK,BLACK,WHITE},
    {BLACK,BLACK,BLACK,WHITE},
    {WHITE,WHITE,WHITE,BLACK}
};

 uint8_t CHAR_T_UP[6][4] = {
    {BLACK,WHITE,WHITE,WHITE},
    {BLACK,BLACK,WHITE,BLACK},
    {BLACK,BLACK,WHITE,BLACK},
    {BLACK,BLACK,WHITE,BLACK},
    {BLACK,BLACK,WHITE,BLACK},
    {BLACK,BLACK,WHITE,BLACK}
};

 uint8_t CHAR_U_UP[6][4] = {
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {BLACK,WHITE,WHITE,BLACK}
};

 uint8_t CHAR_V_UP[6][4] = {
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,WHITE,BLACK},
    {BLACK,WHITE,BLACK,BLACK}
};

 uint8_t CHAR_W_UP[6][4] = {
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,WHITE,WHITE,WHITE},
    {WHITE,BLACK,BLACK,WHITE}
};

 uint8_t CHAR_X_UP[6][4] = {
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {BLACK,WHITE,WHITE,BLACK},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE}
};

 uint8_t CHAR_Y_UP[6][4] = {
    {BLACK,WHITE,BLACK,WHITE},
    {BLACK,WHITE,BLACK,WHITE},
    {BLACK,WHITE,BLACK,WHITE},
    {BLACK,BLACK,WHITE,BLACK},
    {BLACK,BLACK,WHITE,BLACK},
    {BLACK,BLACK,WHITE,BLACK}
};

 uint8_t CHAR_Z_UP[6][4] = {
    {WHITE,WHITE,WHITE,WHITE},
    {BLACK,BLACK,BLACK,WHITE},
    {BLACK,BLACK,WHITE,BLACK},
    {BLACK,WHITE,BLACK,BLACK},
    {WHITE,BLACK,BLACK,BLACK},
    {WHITE,WHITE,WHITE,WHITE}
};