#ifndef VGA_H
#define VGA_H

void vga_init();
void vga_write_buffer_to_screen();
void vga_move_cursor();
void vga_add_char_at_cursor(char c);

//frame buffer constants
#define FB_WIDTH 128        //frane buffer width
#define FB_HEIGHT 96        //frame buffer height
//vga constants
#define TOTAL_LINES   524
#define TOTAL_CYCLES  800
//actual pixel sizes
#define RES_WIDTH 640
#define RES_HEIGHT 480
//video pins
#define HSYNC 6
#define VSYNC 7

//font size definitions
#define CHAR_HEIGHT 6
#define CHAR_WIDTH 4

/* Color definitions, pins for color are as follows: 
 * |0|1|2|3|4|5|6|7|
 * |R|R|G|G|B|B|x|x|
 * the second of each color is a darker shade */

#define RED     0x11000000
#define GREEN   0x00110000
#define BLUE    0x00001100
#define BLACK   0x00000000
#define WHITE   0x11111100
#define YELLOW  0x11110000
#define PURPLE  0x11001100
#define CYAN    0x00111100

#endif
char CHAR_SPACE[6][4] = {
    {BLACK,BLACK,BLACK,BLACK},
    {BLACK,BLACK,BLACK,BLACK},
    {BLACK,BLACK,BLACK,BLACK},
    {BLACK,BLACK,BLACK,BLACK},
    {BLACK,BLACK,BLACK,BLACK},
    {BLACK,BLACK,BLACK,BLACK}
};

char CHAR_A_UP[6][4] = {
    {BLACK,WHITE,WHITE,BLACK},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,WHITE,WHITE,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE}
};

char CHAR_B_UP[6][4] = {
    {WHITE,WHITE,WHITE,BLACK},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,WHITE,WHITE,BLACK},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,WHITE,WHITE,BLACK}
};

char CHAR_C_UP[6][4] = {
    {BLACK,WHITE,WHITE,BLACK},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,BLACK},
    {WHITE,BLACK,BLACK,BLACK},
    {BLACK,WHITE,WHITE,BLACK},
    {WHITE,BLACK,BLACK,WHITE}
};

char CHAR_D_UP[6][4] = {
    {WHITE,WHITE,WHITE,BLACK},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,WHITE,WHITE,BLACK}
};

char CHAR_E_UP[6][4] = {
    {WHITE,WHITE,WHITE,WHITE},
    {WHITE,BLACK,BLACK,BLACK},
    {WHITE,WHITE,WHITE,WHITE},
    {WHITE,BLACK,BLACK,BLACK},
    {WHITE,WHITE,WHITE,WHITE},
    {WHITE,WHITE,WHITE,WHITE}
};

char CHAR_F_UP[6][4] = {
    {WHITE,WHITE,WHITE,WHITE},
    {WHITE,BLACK,BLACK,BLACK},
    {WHITE,BLACK,BLACK,BLACK},
    {WHITE,WHITE,WHITE,BLACK},
    {WHITE,BLACK,BLACK,BLACK},
    {WHITE,BLACK,BLACK,BLACK}
};

char CHAR_G_UP[6][4] = {
    {BLACK,WHITE,WHITE,BLACK},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,BLACK},
    {WHITE,BLACK,WHITE,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {BLACK,WHITE,WHITE,BLACK}
};

char CHAR_H_UP[6][4] = {
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,WHITE,WHITE,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE}
};

char CHAR_I_UP[6][4] = {
    {BLACK,BLACK,WHITE,BLACK},
    {BLACK,BLACK,WHITE,BLACK},
    {BLACK,BLACK,WHITE,BLACK},
    {BLACK,BLACK,WHITE,BLACK},
    {BLACK,BLACK,WHITE,BLACK},
    {BLACK,BLACK,WHITE,BLACK}
};

char CHAR_J_UP[6][4] = {
    {WHITE,WHITE,WHITE,WHITE},
    {BLACK,BLACK,WHITE,BLACK},
    {BLACK,BLACK,WHITE,BLACK},
    {BLACK,BLACK,WHITE,BLACK},
    {BLACK,BLACK,WHITE,BLACK},
    {WHITE,WHITE,BLACK,BLACK}
};

char CHAR_K_UP[6][4] = {
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,WHITE,BLACK},
    {WHITE,WHITE,BLACK,BLACK},
    {WHITE,BLACK,WHITE,BLACK},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE}
};

char CHAR_L_UP[6][4] = {
    {WHITE,BLACK,BLACK,BLACK},
    {WHITE,BLACK,BLACK,BLACK},
    {WHITE,BLACK,BLACK,BLACK},
    {WHITE,BLACK,BLACK,BLACK},
    {WHITE,BLACK,BLACK,BLACK},
    {WHITE,WHITE,WHITE,WHITE}
};

char CHAR_M_UP[6][4] = {
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,WHITE,WHITE,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE}
};

char CHAR_N_UP[6][4] = {
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,WHITE,BLACK,WHITE},
    {WHITE,BLACK,WHITE,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE}
};

char CHAR_O_UP[6][4] = {
    {BLACK,WHITE,WHITE,BLACK},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {BLACK,WHITE,WHITE,BLACK}
};

char CHAR_P_UP[6][4] = {
    {WHITE,WHITE,WHITE,BLACK},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,WHITE,WHITE,BLACK},
    {WHITE,BLACK,BLACK,BLACK},
    {WHITE,BLACK,BLACK,BLACK}
};

char CHAR_Q_UP[6][4] = {
    {BLACK,WHITE,WHITE,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,WHITE,WHITE},
    {BLACK,WHITE,WHITE,BLACK},
    {BLACK,BLACK,BLACK,WHITE}
};

char CHAR_R_UP[6][4] = {
    {WHITE,WHITE,WHITE,BLACK},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,WHITE,WHITE,BLACK},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE}
};

char CHAR_S_UP[6][4] = {
    {BLACK,WHITE,WHITE,WHITE},
    {WHITE,BLACK,BLACK,BLACK},
    {BLACK,WHITE,WHITE,BLACK},
    {BLACK,BLACK,BLACK,WHITE},
    {BLACK,BLACK,BLACK,WHITE},
    {WHITE,WHITE,WHITE,BLACK}
};

char CHAR_T_UP[6][4] = {
    {BLACK,WHITE,WHITE,WHITE},
    {BLACK,BLACK,WHITE,BLACK},
    {BLACK,BLACK,WHITE,BLACK},
    {BLACK,BLACK,WHITE,BLACK},
    {BLACK,BLACK,WHITE,BLACK},
    {BLACK,BLACK,WHITE,BLACK}
};

char CHAR_U_UP[6][4] = {
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {BLACK,WHITE,WHITE,BLACK}
};

char CHAR_V_UP[6][4] = {
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,WHITE,BLACK},
    {BLACK,WHITE,BLACK,BLACK}
};

char CHAR_W_UP[6][4] = {
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,WHITE,WHITE,WHITE},
    {WHITE,BLACK,BLACK,WHITE}
};

char CHAR_X_UP[6][4] = {
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE},
    {BLACK,WHITE,WHITE,BLACK},
    {WHITE,BLACK,BLACK,WHITE},
    {WHITE,BLACK,BLACK,WHITE}
};

char CHAR_Y_UP[6][4] = {
    {BLACK,WHITE,BLACK,WHITE},
    {BLACK,WHITE,BLACK,WHITE},
    {BLACK,WHITE,BLACK,WHITE},
    {BLACK,BLACK,WHITE,BLACK},
    {BLACK,BLACK,WHITE,BLACK},
    {BLACK,BLACK,WHITE,BLACK}
};

char CHAR_Z_UP[6][4] = {
    {WHITE,WHITE,WHITE,WHITE},
    {BLACK,BLACK,BLACK,WHITE},
    {BLACK,BLACK,WHITE,BLACK},
    {BLACK,WHITE,BLACK,BLACK},
    {WHITE,BLACK,BLACK,BLACK},
    {WHITE,WHITE,WHITE,WHITE}
};

#ifndef COORD_STRUCT
#define COORD_STRUCT
struct Coord
{
    int x,y;
};
#endif